# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(505, 260))
        MainWindow.setMaximumSize(QtCore.QSize(505, 260))
        MainWindow.setWindowTitle("NAZA GPS")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 59, 461, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_lon = QtWidgets.QLabel(self.layoutWidget)
        self.label_lon.setFrameShape(QtWidgets.QFrame.Box)
        self.label_lon.setText("")
        self.label_lon.setObjectName("label_lon")
        self.gridLayout.addWidget(self.label_lon, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_spd = QtWidgets.QLabel(self.layoutWidget)
        self.label_spd.setFrameShape(QtWidgets.QFrame.Box)
        self.label_spd.setText("")
        self.label_spd.setObjectName("label_spd")
        self.gridLayout.addWidget(self.label_spd, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_gpsAlt = QtWidgets.QLabel(self.layoutWidget)
        self.label_gpsAlt.setFrameShape(QtWidgets.QFrame.Box)
        self.label_gpsAlt.setText("")
        self.label_gpsAlt.setObjectName("label_gpsAlt")
        self.gridLayout.addWidget(self.label_gpsAlt, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_time = QtWidgets.QLabel(self.layoutWidget)
        self.label_time.setFrameShape(QtWidgets.QFrame.Box)
        self.label_time.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_time.setLineWidth(1)
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 0, 1, 1, 1)
        self.label_lat = QtWidgets.QLabel(self.layoutWidget)
        self.label_lat.setFrameShape(QtWidgets.QFrame.Box)
        self.label_lat.setText("")
        self.label_lat.setObjectName("label_lat")
        self.gridLayout.addWidget(self.label_lat, 3, 3, 1, 1)
        self.label_satelites = QtWidgets.QLabel(self.layoutWidget)
        self.label_satelites.setFrameShape(QtWidgets.QFrame.Box)
        self.label_satelites.setText("")
        self.label_satelites.setObjectName("label_satelites")
        self.gridLayout.addWidget(self.label_satelites, 0, 3, 1, 1)
        self.label_fix = QtWidgets.QLabel(self.layoutWidget)
        self.label_fix.setFrameShape(QtWidgets.QFrame.Box)
        self.label_fix.setText("")
        self.label_fix.setObjectName("label_fix")
        self.gridLayout.addWidget(self.label_fix, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_hdop = QtWidgets.QLabel(self.layoutWidget)
        self.label_hdop.setFrameShape(QtWidgets.QFrame.Box)
        self.label_hdop.setText("")
        self.label_hdop.setObjectName("label_hdop")
        self.gridLayout.addWidget(self.label_hdop, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 461, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_21 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_sysmsg = QtWidgets.QLabel(self.centralwidget)
        self.label_sysmsg.setGeometry(QtCore.QRect(20, 230, 461, 20))
        self.label_sysmsg.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_sysmsg.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sysmsg.setText("")
        self.label_sysmsg.setObjectName("label_sysmsg")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_8.setText(_translate("MainWindow", "经度："))
        self.label_4.setText(_translate("MainWindow", "海拔："))
        self.label.setText(_translate("MainWindow", "时间："))
        self.label_12.setText(_translate("MainWindow", "星数："))
        self.label_6.setText(_translate("MainWindow", "精度："))
        self.label_18.setText(_translate("MainWindow", "纬度："))
        self.label_14.setText(_translate("MainWindow", "类型："))
        self.label_16.setText(_translate("MainWindow", "速度："))
        self.label_21.setText(_translate("MainWindow", "端口："))
        self.pushButton.setText(_translate("MainWindow", "连接"))
